### ISSUE TITLE
Add an `action.yml` file to create an Ritchie CLI Setup action on the Github Marketplace

### ISSUE THREAD

**Issue by GuillaumeFalourd** [ZupIT/ritchie-cli#1019]
## What would you like to be added**:

- A `action.yml` file that would install and initialise Ritchie CLI on a Github runner on any supported OS (ubuntu, macOS and windows).

## Why is this needed**:

- To make it easier to use Ritchie-CLI in Github Action workflows.

## How can it be done

*Suggestion*: _Create a [composite action](https://docs.github.com/en/actions/creating-actions/creating-a-composite-run-steps-action) using shell bash to install and initialise Ritchie CLI._

On V2.11.3, it would be done like this:

```yaml
- name: Install Ritchie CLI
  run: curl -fsSL https://commons-repo.ritchiecli.io/install.sh | bash
  shell: bash

- name: Initialise Ritchie CLI
  run:    echo '{"addCommons":false, "sendMetrics":false, "runType":"local"}' | rit init --stdin
  shell: bash
```

From 2.11.0 it could be done like this:
```yaml
- name: Install Ritchie CLI
  run: curl -fsSL https://commons-repo.ritchiecli.io/install.sh | bash
  shell: bash

- name: Initialise Ritchie CLI
  run: rit init --sendMetrics="no" --addCommons="yes" --runType="local"
  shell: bash
```
